### ISSUE TITLE
Quarry not breaking blocks

### ISSUE THREAD

**Issue by CourtArtanis** [BuildCraft/BuildCraft#2269]
Running Cauldron latest for forge1231, PEX, Prism, Essentials. No worldguard or protection plugins.

I've seen this referenced a few times, but I've already made the [BuildCraft] user an Op on the server. No change.

The quarry setup is default size, the mining drill just stays on one block and tries to break it over and over again. The cracks appear across the block (this case dirt) as if it was to break, then they would reset and repeat.

Version 6.1.5n - Quarries worked perfectly, I then updated to 6.2.2 and the problem appeared.
Thanks

**Comment by hexchain** [comment]
I just ran into the same problem in Cauldron 1272, with Essentials(AntiBuild, Protect and GroupManager). What I did to make it work was:

- Add the following section to `ops.json`:
```
  {
    "uuid": "77456a1f-b9f9-3f84-8863-ddef5b8e2209",
    "name": "[BuildCraft]",
    "level": 4
  },
```
- Add the following section to `plugins/GroupManager/worlds/world/users.yml`:
```
  77456a1f-b9f9-3f84-8863-ddef5b8e2209:
    lastname: "[BuildCraft]"
    group: Player
    subgroups: []
    permissions: []
```
- Do a reload of GroupManager in console: `manload`

Just leaving it here, in case it helps somebody.
